- docs/index.md
See issue https://github.com/tiangolo/dockerswarm.rocks/issues/12
> Add warning about sudo and environment variables

- .github/workflows/deploy-docs.yml
- scripts/netlify-docs.sh
:sparkles: Add GitHub action with auto-deploy
> Add GitHub action with auto-deploy

- docs/portainer.yml
- docs/swarmpit.yml
- docs/swarmprom.yml
- docs/thelounge.yml
- docs/traefik-host-v1.yml
- docs/traefik-host.yml
- docs/traefik-v1.yml
- docs/traefik-v1/traefik-technical-details.md
- docs/traefik-v1/traefik-with-volume.md
- docs/traefik.yml
♻️ Simplify env var not set errors to make them more maintainable and re-usable.
> ♻️ Simplify env var not set errors

- .github/FUNDING.yml
> ✨ Add GitHub Sponsors button

- docs/project-generators.md
Fixes https://github.com/tiangolo/dockerswarm.rocks/issues/30
> Add T.A.D.S. boilerplate

- docs/swarmprom.md
- docs/traefik.md
📝 Add alternative instructions to set password without env var
> 📝 Add alternative instructions to set password without env var

- .github/workflows/latest-changes.yml
👷 Add latest-changes GitHub action
> 👷 Add latest-changes GitHub action

- docs/traefik-host.yml
Fixed wrong port number in the https entrypoint comment
> ✏ Fix typo in comment for traefik-host.yml

- .github/workflows/latest-changes.yml
🐛 Fix config for latest-changes GitHub Action
> 🐛 Fix config for latest-changes GitHub Action

- .github/dependabot.yml
> 👷 Update Dependabot

- README.md
- docs/index.md
- docs/swarm-or-kubernetes.md
- mkdocs.yml
- pyproject.toml
> 🚨 Deprecate website

- .github/workflows/build-docs.yml
- .github/workflows/deploy-docs.yml
- docs/portainer.md
- docs/swarmpit.md
- docs/swarmprom.md
- docs/thelounge.md
- docs/traefik-v1/traefik-technical-details.md
- docs/traefik-v1/traefik.md
- docs/traefik.md
- mkdocs.yml
- pyproject.toml
> 👷 Deploy docs to Cloudflare

- docs/portainer.md
- docs/swarmpit.md
- docs/swarmprom.md
- docs/thelounge.md
- docs/traefik-v1/traefik-technical-details.md
- docs/traefik-v1/traefik.md
- docs/traefik.md
> 📝 Update admonition syntax

- .github/workflows/build-docs.yml
🐛 Fix main branch for building docs
> 🐛 Fix main branch for building docs

- README.md
- docs/index.md
remove real public IPs from docs
> 📝 Do not use real public IPs in docs

- docs/portainer.yml
🔧 Update Portainer
This applies the same change in the removed branch in https://github.com/tiangolo/dockerswarm.rocks/pull/54
> 🔧 Update Portainer

- docs/swarmpit.md
- docs/swarmpit.yml
📝 Tweak Swarmpit to use a new CouchDB with support for ARM
> 📝 Tweak Swarmpit to use a new CouchDB with support for ARM

- .github/workflows/deploy-docs.yml
👷 Update GitHub Actions to download and upload artifacts
> 👷 Update GitHub Actions to download and upload artifacts

- .gitignore
> 🙈 Update gitignore

- .github/workflows/build-docs.yml
- docs/css/custom.css
- docs/css/termynal.css
- docs/js/custom.js
- docs/js/termynal.js
- mkdocs.insiders.yml
- mkdocs.yml
- requirements-docs-insiders.txt
- requirements-docs.txt
- scripts/docs.py
- scripts/mkdocs_hooks.py
> 👷 Upgrade build docs configs

- .github/labeler.yml
- .github/workflows/labeler.yml
> 👷 Add labeler workflow

- .github/workflows/build-docs.yml
- .github/workflows/deploy-docs.yml
> 👷 Use uv for CI
